from enum import Enum

class DataStatus(str, Enum):
    OBSERVED = "OBSERVED"
    FROZEN = "FROZEN"
    OFFICIAL = "OFFICIAL"
    SYNTHETIC = "SYNTHETIC"
    DEMO = "DEMO"

class OutlierStatus(str, Enum):
    VALID = "VALID"
    OUTLIER_FLAGGED = "OUTLIER_FLAGGED"
    EXCLUDED = "EXCLUDED"
    RETAINED_WITH_WARNING = "RETAINED_WITH_WARNING"

class IndexFrequency(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"

class UnavailableReason(str, Enum):
    INSUFFICIENT_OBSERVATIONS = "INSUFFICIENT_OBSERVATIONS"
    MISSING_REFERENCE_PERIOD = "MISSING_REFERENCE_PERIOD"
    MISSING_COMPARISON_PERIOD = "MISSING_COMPARISON_PERIOD"
    VIRTUAL_TRIP_MISMATCH = "VIRTUAL_TRIP_MISMATCH"
    QUALITY_EXCLUSIONS = "QUALITY_EXCLUSIONS"
    MISSING_ROUTE_WEIGHT = "MISSING_ROUTE_WEIGHT"

VALID_HORIZONS = {1, 7, 15, 30, 45}
